version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: next
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: next
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: next
