targets:
  deps-frontend:
    program: "npm"
    args:
      - i
    cwd: frontend
  deps-backend:
    program: go
    args:
      - mod
      - download
    cwd: backend
  build-frontend-wasm:
    program: npm
    args:
      - run
      - wasm
    cwd: frontend
  dev-frontend:
    program: npm
    args:
      - run
      - dev
    cwd: frontend
    before_hooks:
      - build-frontend-wasm
  dev-backend:
    program: go
    args:
      - run
      - .
      - serve
    env_file: .env
    cwd: backend
  dev-docs:
    program: hugo
    args:
      - serve
      - -D
    cwd: site
