version: "3.3"

services:
  note-mark:
    build: .
    container_name: note-mark
    restart: unless-stopped
    volumes:
      - ./.env:/.env:ro
      - note-mark:/data
    ports:
      - 8080:8000

volumes:
  note-mark:
