[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pulldown-cmark = { version = "0.9.3", default-features = false }
wasm-bindgen = "0.2.87"

[profile.release]
lto = true
opt-level = 's'
