[package]
name = "renderer"
version = "0.1.0"
edition = "2021"
description = "markdown renderer for Note Mark frontend"
repository = "https://github.com/enchant97/note-mark"
license = "AGPL-3.0-only"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
liquid = "0.26.9"
pulldown-cmark = { version = "0.12.1", default-features = false, features = [ "html" ] }
serde = { version = "1.0.215", features = ["derive"] }
wasm-bindgen = "0.2.93"

[profile.release]
lto = true
opt-level = 's'
