# file: docker-compose.yml
# built-for: 0.17
volumes:
  data:

services:
  note-mark:
    image: ghcr.io/enchant97/note-mark-aio
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      # !!! REPLACE These !!!
      JWT_SECRET: "!!! REPLACE ME !!!"
      CORS_ORIGINS: "http://example.com"
    ports:
      - 80:8000
