# file: docker-compose.yml
# built-for: 0.17
volumes:
  note_mark_data:
  postgres_data:

services:
  note_mark:
    image: ghcr.io/enchant97/note-mark-aio
    restart: unless-stopped
    volumes:
      - note_mark_data:/data
    environment:
      JWT_SECRET: "!!! REPLACE ME !!!"
      CORS_ORIGINS: "http://example.com"
      DB__TYPE: postgres
      DB__URI: "host=postgres user=postgres password=postgres dbname=notemark port=5432 sslmode=disable TimeZone=Europe/London"
    ports:
      - 80:8000

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: notemark
      POSTGRES_USER: postgres
      # !!! REPLACE !!!
      POSTGRES_PASSWORD: postgres
